module "wrapper" {
  source = "../"

  for_each = var.items

  air_gapped_vault_kms_key_arn        = try(each.value.air_gapped_vault_kms_key_arn, var.defaults.air_gapped_vault_kms_key_arn, null)
  air_gapped_vault_max_retention_days = try(each.value.air_gapped_vault_max_retention_days, var.defaults.air_gapped_vault_max_retention_days, 35)
  air_gapped_vault_min_retention_days = try(each.value.air_gapped_vault_min_retention_days, var.defaults.air_gapped_vault_min_retention_days, 7)
  air_gapped_vault_name               = try(each.value.air_gapped_vault_name, var.defaults.air_gapped_vault_name, null)
  attach_vault_policy                 = try(each.value.attach_vault_policy, var.defaults.attach_vault_policy, false)
  create                              = try(each.value.create, var.defaults.create, true)
  create_air_gapped_vault             = try(each.value.create_air_gapped_vault, var.defaults.create_air_gapped_vault, false)
  create_iam_role                     = try(each.value.create_iam_role, var.defaults.create_iam_role, true)
  create_iam_role_additional_policy   = try(each.value.create_iam_role_additional_policy, var.defaults.create_iam_role_additional_policy, false)
  create_vault                        = try(each.value.create_vault, var.defaults.create_vault, true)
  existing_vault_name                 = try(each.value.existing_vault_name, var.defaults.existing_vault_name, null)
  iam_role_additional_policy_arns     = try(each.value.iam_role_additional_policy_arns, var.defaults.iam_role_additional_policy_arns, [])
  iam_role_additional_policy_json     = try(each.value.iam_role_additional_policy_json, var.defaults.iam_role_additional_policy_json, null)
  iam_role_arn                        = try(each.value.iam_role_arn, var.defaults.iam_role_arn, null)
  iam_role_attach_s3_policies         = try(each.value.iam_role_attach_s3_policies, var.defaults.iam_role_attach_s3_policies, true)
  iam_role_name                       = try(each.value.iam_role_name, var.defaults.iam_role_name, null)
  iam_role_path                       = try(each.value.iam_role_path, var.defaults.iam_role_path, null)
  iam_role_permissions_boundary       = try(each.value.iam_role_permissions_boundary, var.defaults.iam_role_permissions_boundary, null)
  name                                = try(each.value.name, var.defaults.name)
  plans                               = try(each.value.plans, var.defaults.plans, {})
  region                              = try(each.value.region, var.defaults.region, null)
  tags                                = try(each.value.tags, var.defaults.tags, {})
  vault_copy_source_account_ids       = try(each.value.vault_copy_source_account_ids, var.defaults.vault_copy_source_account_ids, [])
  vault_force_destroy                 = try(each.value.vault_force_destroy, var.defaults.vault_force_destroy, false)
  vault_kms_key_arn                   = try(each.value.vault_kms_key_arn, var.defaults.vault_kms_key_arn, null)
  vault_lock_changeable_for_days      = try(each.value.vault_lock_changeable_for_days, var.defaults.vault_lock_changeable_for_days, null)
  vault_lock_enabled                  = try(each.value.vault_lock_enabled, var.defaults.vault_lock_enabled, false)
  vault_lock_max_retention_days       = try(each.value.vault_lock_max_retention_days, var.defaults.vault_lock_max_retention_days, null)
  vault_lock_min_retention_days       = try(each.value.vault_lock_min_retention_days, var.defaults.vault_lock_min_retention_days, null)
  vault_name                          = try(each.value.vault_name, var.defaults.vault_name, null)
  vault_notifications_enabled         = try(each.value.vault_notifications_enabled, var.defaults.vault_notifications_enabled, false)
  vault_notifications_events          = try(each.value.vault_notifications_events, var.defaults.vault_notifications_events, ["BACKUP_JOB_FAILED", "COPY_JOB_FAILED", "RESTORE_JOB_FAILED"])
  vault_notifications_sns_topic_arn   = try(each.value.vault_notifications_sns_topic_arn, var.defaults.vault_notifications_sns_topic_arn, null)
  vault_policy                        = try(each.value.vault_policy, var.defaults.vault_policy, null)
}
